services:

  express-app:
    image: sjmy/express-app:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: express-app

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CONTAINER_NAMES=express-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower